/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.hansight.kunlun.collector.common.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Event extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Event\",\"namespace\":\"com.hansight.kunlun.collector.common.model\",\"fields\":[{\"name\":\"header\",\"type\":[{\"type\":\"map\",\"values\":\"string\"},\"null\"]},{\"name\":\"body\",\"type\":[\"bytes\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> header;
  @Deprecated public java.nio.ByteBuffer body;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Event() {}

  /**
   * All-args constructor.
   */
  public Event(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> header, java.nio.ByteBuffer body) {
    this.header = header;
    this.body = body;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return header;
    case 1: return body;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: header = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    case 1: body = (java.nio.ByteBuffer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'header' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getHeader() {
    return header;
  }

  /**
   * Sets the value of the 'header' field.
   * @param value the value to set.
   */
  public void setHeader(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.header = value;
  }

  /**
   * Gets the value of the 'body' field.
   */
  public java.nio.ByteBuffer getBody() {
    return body;
  }

  /**
   * Sets the value of the 'body' field.
   * @param value the value to set.
   */
  public void setBody(java.nio.ByteBuffer value) {
    this.body = value;
  }

  /** Creates a new Event RecordBuilder */
  public static com.hansight.kunlun.collector.common.model.Event.Builder newBuilder() {
    return new com.hansight.kunlun.collector.common.model.Event.Builder();
  }
  
  /** Creates a new Event RecordBuilder by copying an existing Builder */
  public static com.hansight.kunlun.collector.common.model.Event.Builder newBuilder(com.hansight.kunlun.collector.common.model.Event.Builder other) {
    return new com.hansight.kunlun.collector.common.model.Event.Builder(other);
  }
  
  /** Creates a new Event RecordBuilder by copying an existing Event instance */
  public static com.hansight.kunlun.collector.common.model.Event.Builder newBuilder(com.hansight.kunlun.collector.common.model.Event other) {
    return new com.hansight.kunlun.collector.common.model.Event.Builder(other);
  }
  
  /**
   * RecordBuilder for Event instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Event>
    implements org.apache.avro.data.RecordBuilder<Event> {

    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> header;
    private java.nio.ByteBuffer body;

    /** Creates a new Builder */
    private Builder() {
      super(com.hansight.kunlun.collector.common.model.Event.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.hansight.kunlun.collector.common.model.Event.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.header)) {
        this.header = data().deepCopy(fields()[0].schema(), other.header);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.body)) {
        this.body = data().deepCopy(fields()[1].schema(), other.body);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Event instance */
    private Builder(com.hansight.kunlun.collector.common.model.Event other) {
            super(com.hansight.kunlun.collector.common.model.Event.SCHEMA$);
      if (isValidValue(fields()[0], other.header)) {
        this.header = data().deepCopy(fields()[0].schema(), other.header);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.body)) {
        this.body = data().deepCopy(fields()[1].schema(), other.body);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'header' field */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getHeader() {
      return header;
    }
    
    /** Sets the value of the 'header' field */
    public com.hansight.kunlun.collector.common.model.Event.Builder setHeader(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[0], value);
      this.header = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'header' field has been set */
    public boolean hasHeader() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'header' field */
    public com.hansight.kunlun.collector.common.model.Event.Builder clearHeader() {
      header = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'body' field */
    public java.nio.ByteBuffer getBody() {
      return body;
    }
    
    /** Sets the value of the 'body' field */
    public com.hansight.kunlun.collector.common.model.Event.Builder setBody(java.nio.ByteBuffer value) {
      validate(fields()[1], value);
      this.body = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'body' field has been set */
    public boolean hasBody() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'body' field */
    public com.hansight.kunlun.collector.common.model.Event.Builder clearBody() {
      body = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Event build() {
      try {
        Event record = new Event();
        record.header = fieldSetFlags()[0] ? this.header : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[0]);
        record.body = fieldSetFlags()[1] ? this.body : (java.nio.ByteBuffer) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
